addons:
  code_climate:
    repo_token: 7489b72ccd410b8edb3d73e9181b4cfbdb25f38b2fbc717b96d5b3a743b47188
branches:
  except:
    - gh-pages
cache: bundler
env:
  - COVERAGE=true
language: ruby
notifications:
  email:
    - dev@bitaculous.com
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
sudo: false